### ISSUE TITLE
Use stealth to make puppeteer more like a normal browser

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-wechat#108]
See: https://www.npmjs.com/package/puppeteer-extra-plugin-stealth

**Comment by huan** [comment]
@sososoyoung Would you like to have a look at this issue?

**Comment by sososoyoung** [comment]
@huan No problem. I will have a look this weekend.

**Comment by suntong** [comment]
Can it be closed since it's been merged already?

**Comment by suntong** [comment]
Try closing it. 
Let me know otherwise, and I'll reopen it.
