### ISSUE TITLE
主动下线，或者被挤下线后，重新登录报web登录的错误

### ISSUE THREAD

**Issue by ForeverZhong** [wechaty/wechaty-puppet-wechat#140]
主动下线，或者被挤下线后，重新登录报web登录的错误

**Comment by xiaowx-mau** [comment]
I've the same error. When I restart the nodejs server. The error was recovered.

**Comment by huan** [comment]
Could you please provide your wechaty & wechaty-puppet-wechat version by running `npm ls` under your project folder, and make sure you are using the latest version of the modules?

Here's a PR for solving this issue: #130, which makes me believe this issue has already been solved already.

**Comment by xiaowx-mau** [comment]
[version.txt](https://github.com/wechaty/wechaty-puppet-wechat/files/6914636/version.txt)
Here is the version list.
wechaty@0.62.3
wechaty-puppet@0.41.7
wechaty-puppet-service@0.21.11
wechaty-puppet-wechat@0.28.3

**Comment by ForeverZhong** [comment]
我通过监听掉线，掉线后重新实例一个新的机器人暂时解决了这个问题。&nbsp;

(.∩_∩.)开开心心生活,努努力力学习,接着就是天天向上拉!
 &nbsp;


&nbsp;

**Comment by huan** [comment]
@leochen-g it seems our last PR has not fixed this problem. Could you please help us to inspect the code and to see if there's anything we missed?

**Comment by leochen-g** [comment]
> @leochen-g it seems our last PR has not fixed this problem. Could you please help us to inspect the code and to see if there's anything we missed?

ok , I will check it

**Comment by leochen-g** [comment]
> @leochen-g it seems our last PR has not fixed this problem. Could you please help us to inspect the code and to see if there's anything we missed?

已经提交PR 修复 #147

**Comment by leochen-g** [comment]
> [version.txt](https://github.com/wechaty/wechaty-puppet-wechat/files/6914636/version.txt)
> Here is the version list.
> wechaty@0.62.3
> wechaty-puppet@0.41.7
> wechaty-puppet-service@0.21.11
> wechaty-puppet-wechat@0.28.3

更新wechaty-puppet-wechat版本到0.28.4， 如果发现版本不存在的话，切换npm源为npm的源，其他源可能还没同步过去

**Comment by huan** [comment]
@leochen-g Thank you very much for the quick fix, appreciate it!

**Comment by xiaowx-mau** [comment]
> > [version.txt](https://github.com/wechaty/wechaty-puppet-wechat/files/6914636/version.txt)
> > Here is the version list.
> > wechaty@0.62.3
> > wechaty-puppet@0.41.7
> > wechaty-puppet-service@0.21.11
> > wechaty-puppet-wechat@0.28.3
> 
> 更新wechaty-puppet-wechat版本到0.28.4， 如果发现版本不存在的话，切换npm源为npm的源，其他源可能还没同步过去

更新后问题已经修复。再请问下wechaty docker什么时候可以修复呢

**Comment by huan** [comment]
@xiaowx-mau Thanks for the confirmation.

The wechaty docker image will be rebuild every time that the wechaty has a new version.

A PR will be welcome if you like to trigger it.

**Comment by xiaowx-mau** [comment]
> @xiaowx-mau Thanks for the confirmation.
> 
> The wechaty docker image will be rebuild every time that the wechaty has a new version.
> 
> A PR will be welcome if you like to trigger it.

Thanks for the explanation.
Hope I achieve this achievement . :smirk:

**Comment by huan** [comment]
Looking forward to that!

**Comment by huan** [comment]
Close this issue because the problem has been resolved.
